version: '3.8'

services:
    app:
        image: devsos/academy-sre-bootcamp-santiago-orozco:latest
        build:
            context: .
        container_name: node_app
        environment:
            - 'DB_HOST=${DB_HOST}'
            - 'DB_USER=${DB_USER}'
            - 'DB_PASSWORD=${DB_PASSWORD}'
            - 'DB_DATABASE=${DB_DATABASE}'
            - 'JWT_KEY=${JWT_KEY}'
        ports:
            - '8000:8000'
